################################################################################
# Mac mini workstation build
#
# There is no first-party Terraform provider for macOS, so this configuration
# treats the local machine as the "infrastructure" and drives it with
# terraform_data resources and local-exec provisioners.
#
# Each block is idempotent and carries a triggers_replace value, so changing a
# variable re-runs only the block that depends on it instead of the whole file.
#
# Usage:
#   sudo -v                       # cache admin credentials for this session
#   terraform init
#   terraform plan
#   terraform apply
################################################################################

locals {
  state_dir      = pathexpand(var.state_dir)
  brewfile_path  = "${local.state_dir}/Brewfile"
  screenshot_dir = pathexpand(var.screenshot_dir)

  # Bonjour/local host names cannot contain spaces.
  host_name = replace(var.computer_name, " ", "-")

  # Sourced by every provisioner so brew is on PATH on both Apple silicon
  # (/opt/homebrew) and Intel (/usr/local) hardware.
  brew_shellenv = <<-EOT
    if [ -x /opt/homebrew/bin/brew ]; then
      eval "$(/opt/homebrew/bin/brew shellenv)"
    elif [ -x /usr/local/bin/brew ]; then
      eval "$(/usr/local/bin/brew shellenv)"
    fi
  EOT

  brewfile_content = join("\n", concat(
    ["# Generated by Terraform - edits will be overwritten on the next apply.", ""],
    [for f in var.homebrew_formulae : format("brew %q", f)],
    [""],
    [for c in var.homebrew_casks : format("cask %q", c)],
    [""],
    [for name, id in var.mas_apps : format("mas %q, id: %d", name, id)],
    [""],
  ))
}

################################################################################
# Preflight - fail early with a readable message instead of halfway through
################################################################################

resource "terraform_data" "preflight" {
  provisioner "local-exec" {
    interpreter = ["/bin/bash", "-c"]
    command     = <<-EOT
      set -euo pipefail

      if [ "$(uname -s)" != "Darwin" ]; then
        echo "ERROR: this configuration only runs on macOS (found $(uname -s))." >&2
        exit 1
      fi

      if ! sudo -n true 2>/dev/null; then
        echo "ERROR: cached admin credentials are required." >&2
        echo "       Run 'sudo -v' in this terminal, then re-run terraform apply." >&2
        exit 1
      fi

      echo "Preflight OK: $(sw_vers -productName) $(sw_vers -productVersion) on $(uname -m)"
    EOT
  }
}

################################################################################
# Identity: computer, host and Bonjour names
################################################################################

resource "terraform_data" "computer_name" {
  depends_on = [terraform_data.preflight]

  triggers_replace = [var.computer_name]

  provisioner "local-exec" {
    interpreter = ["/bin/bash", "-c"]
    command     = <<-EOT
      set -euo pipefail
      sudo scutil --set ComputerName  "${var.computer_name}"
      sudo scutil --set HostName      "${local.host_name}"
      sudo scutil --set LocalHostName "${local.host_name}"
      sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server \
        NetBIOSName -string "${local.host_name}"
    EOT
  }
}

################################################################################
# Time zone and network time
################################################################################

resource "terraform_data" "time_zone" {
  depends_on = [terraform_data.preflight]

  triggers_replace = [var.time_zone]

  provisioner "local-exec" {
    interpreter = ["/bin/bash", "-c"]
    command     = <<-EOT
      set -euo pipefail
      sudo systemsetup -settimezone "${var.time_zone}" >/dev/null
      sudo systemsetup -setusingnetworktime on >/dev/null
      echo "Time zone set to $(systemsetup -gettimezone | cut -d: -f2 | xargs)"
    EOT
  }
}

################################################################################
# Homebrew and packages
################################################################################

resource "terraform_data" "homebrew" {
  depends_on = [terraform_data.preflight]

  provisioner "local-exec" {
    interpreter = ["/bin/bash", "-c"]
    command     = <<-EOT
      set -euo pipefail
      ${local.brew_shellenv}

      if command -v brew >/dev/null 2>&1; then
        echo "Homebrew already installed at $(brew --prefix)"
      else
        echo "Installing Homebrew..."
        NONINTERACTIVE=1 /bin/bash -c \
          "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      fi
    EOT
  }
}

resource "terraform_data" "brew_bundle" {
  depends_on = [terraform_data.homebrew]

  # Re-runs whenever the package list changes.
  triggers_replace = [sha256(local.brewfile_content)]

  provisioner "local-exec" {
    interpreter = ["/bin/bash", "-c"]
    command     = <<-EOT
      set -euo pipefail
      ${local.brew_shellenv}

      mkdir -p "${local.state_dir}"
      cat > "${local.brewfile_path}" <<'BREWFILE'
      ${local.brewfile_content}
      BREWFILE

      brew update
      brew bundle install --file "${local.brewfile_path}" --no-upgrade
      brew cleanup
    EOT
  }
}

################################################################################
# Desktop preferences (Dock, Finder, screenshots, keyboard)
################################################################################

resource "terraform_data" "dock" {
  depends_on = [terraform_data.preflight]

  triggers_replace = [var.dock_tile_size, var.dock_autohide]

  provisioner "local-exec" {
    interpreter = ["/bin/bash", "-c"]
    command     = <<-EOT
      set -euo pipefail
      defaults write com.apple.dock tilesize         -int  ${var.dock_tile_size}
      defaults write com.apple.dock autohide         -bool ${var.dock_autohide}
      defaults write com.apple.dock show-recents     -bool false
      defaults write com.apple.dock mru-spaces       -bool false
      killall Dock || true
    EOT
  }
}

resource "terraform_data" "finder" {
  depends_on = [terraform_data.preflight]

  triggers_replace = [var.show_hidden_files]

  provisioner "local-exec" {
    interpreter = ["/bin/bash", "-c"]
    command     = <<-EOT
      set -euo pipefail
      defaults write com.apple.finder AppleShowAllFiles      -bool ${var.show_hidden_files}
      defaults write NSGlobalDomain AppleShowAllExtensions   -bool ${var.show_hidden_files}
      defaults write com.apple.finder ShowPathbar             -bool true
      defaults write com.apple.finder ShowStatusBar           -bool true
      defaults write com.apple.finder FXPreferredViewStyle    -string "Nlsv"
      # Do not litter network and USB volumes with .DS_Store files
      defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
      defaults write com.apple.desktopservices DSDontWriteUSBStores     -bool true
      killall Finder || true
    EOT
  }
}

resource "terraform_data" "screenshots" {
  depends_on = [terraform_data.preflight]

  triggers_replace = [local.screenshot_dir]

  provisioner "local-exec" {
    interpreter = ["/bin/bash", "-c"]
    command     = <<-EOT
      set -euo pipefail
      mkdir -p "${local.screenshot_dir}"
      defaults write com.apple.screencapture location -string "${local.screenshot_dir}"
      defaults write com.apple.screencapture type     -string "png"
      defaults write com.apple.screencapture disable-shadow -bool true
      killall SystemUIServer || true
    EOT
  }
}

resource "terraform_data" "keyboard" {
  depends_on = [terraform_data.preflight]

  triggers_replace = [var.fast_key_repeat]

  provisioner "local-exec" {
    interpreter = ["/bin/bash", "-c"]
    command     = <<-EOT
      set -euo pipefail
      %{if var.fast_key_repeat~}
      defaults write NSGlobalDomain KeyRepeat        -int 2
      defaults write NSGlobalDomain InitialKeyRepeat -int 15
      %{else~}
      defaults delete NSGlobalDomain KeyRepeat        2>/dev/null || true
      defaults delete NSGlobalDomain InitialKeyRepeat 2>/dev/null || true
      %{endif~}
      # Press-and-hold repeats the character instead of showing the accent menu
      defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false
      echo "Keyboard settings apply to apps started after the next log out."
    EOT
  }
}

################################################################################
# Security and remote access
################################################################################

resource "terraform_data" "security" {
  depends_on = [terraform_data.preflight]

  triggers_replace = [var.enable_firewall, var.require_password_after_sleep]

  provisioner "local-exec" {
    interpreter = ["/bin/bash", "-c"]
    command     = <<-EOT
      set -euo pipefail
      FW=/usr/libexec/ApplicationFirewall/socketfilterfw

      sudo "$FW" --setglobalstate ${var.enable_firewall ? "on" : "off"} >/dev/null
      sudo "$FW" --setstealthmode ${var.enable_firewall ? "on" : "off"} >/dev/null
      sudo "$FW" --setloggingmode on >/dev/null

      defaults write com.apple.screensaver askForPassword      -int ${var.require_password_after_sleep ? 1 : 0}
      defaults write com.apple.screensaver askForPasswordDelay -int 0

      # Report FileVault state - enabling it needs an interactive login, so it
      # is surfaced rather than forced.
      fdesetup status
    EOT
  }
}

resource "terraform_data" "remote_login" {
  depends_on = [terraform_data.preflight]

  triggers_replace = [var.enable_remote_login]

  provisioner "local-exec" {
    interpreter = ["/bin/bash", "-c"]
    command     = <<-EOT
      set -euo pipefail
      sudo systemsetup -f -setremotelogin ${var.enable_remote_login ? "on" : "off"} >/dev/null
      sudo systemsetup -getremotelogin
    EOT
  }
}

resource "terraform_data" "software_updates" {
  depends_on = [terraform_data.preflight]

  triggers_replace = [var.auto_software_updates]

  provisioner "local-exec" {
    interpreter = ["/bin/bash", "-c"]
    command     = <<-EOT
      set -euo pipefail
      SU=/Library/Preferences/com.apple.SoftwareUpdate
      ON=${var.auto_software_updates}

      sudo defaults write "$SU" AutomaticCheckEnabled    -bool "$ON"
      sudo defaults write "$SU" AutomaticDownload        -bool "$ON"
      sudo defaults write "$SU" CriticalUpdateInstall    -bool "$ON"
      sudo defaults write "$SU" ConfigDataInstall        -bool "$ON"
      sudo defaults write /Library/Preferences/com.apple.commerce AutoUpdate -bool "$ON"
    EOT
  }
}

################################################################################
# Power - an always-on mini should not sleep and should come back by itself
################################################################################

resource "terraform_data" "power" {
  depends_on = [terraform_data.preflight]

  triggers_replace = [var.server_power_profile]

  provisioner "local-exec" {
    interpreter = ["/bin/bash", "-c"]
    command     = <<-EOT
      set -euo pipefail
      %{if var.server_power_profile~}
      sudo pmset -a sleep 0 disksleep 0 displaysleep 15 womp 1 autorestart 1 powernap 0
      sudo systemsetup -setrestartfreeze on >/dev/null
      %{else~}
      sudo pmset -a sleep 10 disksleep 10 displaysleep 10 womp 0 autorestart 0
      %{endif~}
      pmset -g custom
    EOT
  }
}

################################################################################
# Home directory layout
################################################################################

resource "terraform_data" "project_directories" {
  depends_on = [terraform_data.preflight]

  triggers_replace = [var.project_directories]

  provisioner "local-exec" {
    interpreter = ["/bin/bash", "-c"]
    command     = <<-EOT
      set -euo pipefail
      %{for dir in var.project_directories~}
      mkdir -p "${pathexpand(dir)}"
      %{endfor~}
    EOT
  }
}
